# Generated by Django 4.2.3 on 2023-07-11 02:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characterLevel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(40)])),
                ('experience', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_in_gold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('armor_bonus', models.IntegerField()),
                ('max_dex_bonus', models.IntegerField()),
                ('arcane_spell_failure_percent_chance', models.IntegerField()),
                ('speed_base_30', models.IntegerField(blank=True, null=True)),
                ('speed_base_20', models.IntegerField(blank=True, null=True)),
            ],
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('damage', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('category', models.CharField(choices=[('light', 'Light'), ('one_handed', 'one-handed'), ('two_handed', 'two_handed')], max_length=20)),
                ('proficiency', models.CharField(choices=[('martial', 'Martial'), ('simple', 'Simple'), ('exotice', 'Exotic')], max_length=20)),
            ],
            bases=('inventory.item',),
        ),
    ]
