# Generated by Django 4.2.3 on 2023-07-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='inventory.item')),
            ],
        ),
    ]
