# Generated by Django 4.2.3 on 2023-07-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_item_inventory_item_id_alter_item_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
