# Generated by Django 4.2.3 on 2023-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='character',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
