# Generated by Django 4.2.4 on 2023-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_name_character_first_name_character_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
